name: Deploy AWS Glue Job

on:
  push:
    branches:
      - main  # Runs the pipeline when code is pushed to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS Credentials (Set up AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY in GitHub Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3️⃣ Upload Glue Script to S3
      - name: Upload Glue Script to S3
        run: |
          aws s3 cp glue_etl.py s3://ag-my-data-lake-etl-bucket/glue-scripts/

    #   # 4️⃣ Start AWS Glue Job
    #   - name: Start AWS Glue Job
    #     run: |
    #       aws glue start-job-run --job-name glue-etl-job

    #   # 5️⃣ Notify on Failure
    #   - name: Notify on Failure
    #     if: failure()
    #     run: echo "AWS Glue job execution failed!"
